// data-pregens.js — Ch.8 hero stat blocks, instantiable as pre-generated characters.
// Ruling R2: the book sanctions playing established characters. These are NPC-economy stat blocks —
// their Health and Resolve are the published values, not re-derived from a point buy. The app marks
// pregen characters accordingly so the wizard's legality checks are not applied retroactively.
// Mechanics only; no plot or setting text.

const A = (f, a, s, r, i, p) => ({ fighting: f, agility: a, strength: s, reason: r, intuition: i, presence: p });

export const PREGENS = [
  { name: "Allen the Alien", asOf: "Return to report on Omni-Man", role: "Defender", occupation: "Adventurer",
    descriptor: "Genetically enhanced champion evaluator, funny and brave.",
    personality: ["Funny", "Friendly"], drive: "Victory.", flaw: "Motormouth.", reputation: 4, resources: 4,
    attrs: A(8, 6, 9, 3, 3, 6), health: 16, resolve: 8, slugfest: 5,
    powerSource: "Enhanced physiology",
    powers: ["Massive FLIGHT (8 zones; Boost: Interstellar Flight)", "LIFE SUPPORT", "Massive PROTECTION (Armor 4)",
      "QUICKNESS", "REGENERATION", "TELEPATHY"],
    talents: ["Charger", "Determined", "Durable ×2", "Hard Hitter", "Resilience", "Second Wind"] },
  { name: "Atom Eve", asOf: "First Omnipotus encounter", role: "Controller", occupation: "Student",
    descriptor: "Matter manipulator and empathetic idealist.",
    personality: ["Empathetic", "Idealistic"], drive: "Compassion.", flaw: "Uncertain.", reputation: 2, resources: 2,
    attrs: A(3, 5, 3, 5, 4, 6), health: 6, resolve: 10, slugfest: 2,
    powerSource: "Bioengineering",
    powers: ["BARRIER (Armor 3)", "BLAST (Damage 3, Range 0/3)", "FLIGHT (2 zones)",
      "Major MATTER CONTROL (weight rating 6)", "Major TRANSFORMATION (weight rating 6)"],
    talents: ["Determined", "Knowledgeable (Natural Sciences)"] },
  { name: "Best Tiger", asOf: "Joining the Guardians of the Globe", role: "Blaster", occupation: "Secret Agent",
    descriptor: "Blindfolded marksman and martial artist.",
    personality: ["Focused", "Laconic"], drive: "Crimefighting.", flaw: "Intense.", reputation: 3, resources: 4,
    attrs: A(6, 8, 4, 5, 8, 3), health: 9, resolve: 8, slugfest: 2,
    powerSource: "Exceptional training",
    powers: ["BLAST (Damage 3, Range 0/3; Boosts: Burst Effect, Deadly Blast)", "ENHANCED SENSES",
      "DEFIANCE (Armor 3 vs stress, +3 dice to resist)", "SWINGING (2 zones)"],
    talents: ["Coordinated", "Evasive", "Martial Arts", "Rapid Fire", "Stealthy"] },
  { name: "Black Samson", asOf: "Recovery of his powers", role: "Brawn", occupation: "Adventurer",
    descriptor: "Veteran strongman with restored abilities.",
    personality: ["Brave", "Experienced"], drive: "Heroism.", flaw: "Critical.", reputation: 5, resources: 7,
    attrs: A(7, 4, 8, 3, 5, 4), health: 12, resolve: 6, slugfest: 4,
    powerSource: "Enhanced physiology",
    powers: ["Major LEAPING (4 zones)", "Major PROTECTION (Armor 3)"],
    talents: ["Durable", "Hard Hitter", "Indomitable"] },
  { name: "Bolt", asOf: "Joining Capes, Inc.", role: "Defender", occupation: "Adventurer",
    descriptor: "Lightning-transformed professional hero on the clock.",
    personality: ["Likable", "Focused"], drive: "Prosperity.", flaw: "On the Clock.", reputation: 4, resources: 4,
    attrs: A(6, 5, 7, 3, 4, 6), health: 11, resolve: 7, slugfest: 4,
    powerSource: "Electro-infused physiology",
    powers: ["Major LEAPING (4 zones)", "PROTECTION (Armor 2)"],
    talents: ["Defensive", "Durable", "Resilience"] },
  { name: "Brit", asOf: "Leading the third Guardians roster", role: "Leader", occupation: "Soldier",
    descriptor: "Invulnerable veteran soldier and commander.",
    personality: ["Battlehardened", "Down-to-earth"], drive: "Vigilance.", flaw: "World-worn.", reputation: 6, resources: 6,
    attrs: A(8, 5, 5, 5, 6, 8), health: 9, resolve: 12, slugfest: 4,
    powerSource: "Invulnerability serum / supplied gear / military expertise",
    powers: ["Monstrous PROTECTION (Armor 5; Boost: Impervious)", "FLIGHT (jet boots, 2 zones)", "STRIKE (jet gloves, +1)",
      "DEFIANCE (Armor 3 vs stress, +3 dice to resist)", "GUIDANCE"],
    talents: ["Combat Veteran", "Commander", "Determined", "Guardian", "Leader", "Tactical Support"],
    special: ["Invulnerability (unique): he cannot take damage to Health — any damage exceeding his Armor becomes stress instead. Foes theorise other routes: suffocation, removal from the battlefield, or mind control."] },
  { name: "Bulletproof", asOf: "Recovery after Battle Beast", role: "Defender", occupation: "Artist",
    descriptor: "Kinetic-absorbing flier with a sharp sense of justice.",
    personality: ["Pragmatic", "Cynical"], drive: "Respect.", flaw: "Outspoken.", reputation: 1, resources: 2,
    attrs: A(6, 6, 7, 2, 5, 4), health: 10, resolve: 6, slugfest: 4,
    powerSource: "Illicit experiment",
    powers: ["Major FLIGHT (4 zones)", "Major PROTECTION (Armor 3; Boost: Energy Absorption)"],
    talents: ["Guardian", "Supportive"] },
  { name: "Claire Voyant", asOf: "The Supreme Leader Cho confrontation", role: "Brains", occupation: "Adventurer",
    descriptor: "Psychic free spirit with wide-ranging mental powers.",
    personality: ["Passionate", "Open-minded"], drive: "Thrills.", flaw: "Capricious.", reputation: 3, resources: 4,
    attrs: A(4, 5, 3, 3, 5, 6), health: 6, resolve: 9, slugfest: 2,
    powerSource: "Psionics",
    powers: ["CLAIRVOYANCE", "FLIGHT (2 zones)", "MIND CONTROL", "Major TELEKINESIS (weight rating 6)", "TELEPATHY"],
    talents: ["Compelling", "Determined"] },
  { name: "Damien Darkblood", asOf: "The Guardians murder investigation", role: "Wildcard", occupation: "Investigator",
    descriptor: "Hellborn detective working off a debt through good deeds.",
    personality: ["Composed", "Creepy"], drive: "Atonement.", flaw: "Obstinate.", reputation: 4, resources: 3,
    attrs: A(4, 4, 5, 6, 8, 5), health: 7, resolve: 10, slugfest: 3,
    powerSource: "Demonic physiology",
    powers: ["DIMENSIONAL TRAVEL (Boost: Quick Travel; Limit: Specific Dimension)", "ENHANCED SENSES", "IMMUNITY (heat)",
      "IMMORTALITY", "LIFE SUPPORT", "POSTCOGNITION", "PROTECTION (Armor 2)", "REGENERATION", "SORCERY",
      "TELEPORTATION (2 zones; Boost: Distant Travel)"],
    talents: ["Investigator", "Knowledgeable (Esoteric Lore)"],
    drawbacks: ["Banishment: can be forcibly exorcised by an arcane ritual known to the magical elite."] },
  { name: "Darkwing", asOf: "Before the Omni-Man attack", role: "Brains", occupation: "Privileged",
    descriptor: "Gadget-driven crimefighter and city protector.",
    personality: ["Motivated", "Sophisticated"], drive: "Vengeance.", flaw: "Closed-off.", reputation: 5, resources: 8,
    attrs: A(8, 5, 4, 4, 5, 4), health: 9, resolve: 9, slugfest: 2,
    powerSource: "Specialized gadgetry",
    powers: ["BLAST (Damage 3, Range 0/3; Boost: Burst Effect)", "FLIGHT (hoverboard, 2 zones)", "PROTECTION (Armor 2)", "SNARE"],
    talents: ["Determined", "Investigator", "Martial Arts", "Stealthy", "Streetwise"],
    drawbacks: ["Obsessed (eradicating crime)"] },
  { name: "Dupli-Kate", asOf: "First Omnipotus encounter", role: "Controller", occupation: "Adventurer",
    descriptor: "Self-cloning martial artist and battlefield coordinator.",
    personality: ["Confident", "Independent"], drive: "Identity.", flaw: "Jaded.", reputation: 2, resources: 2,
    attrs: A(8, 6, 5, 3, 4, 4), health: 10, resolve: 8, slugfest: 4,
    powerSource: "Ancestral curse",
    powers: ["Major DUPLICATION (copy bonus +5; Boost: Sequestered Original; Limit: Traumatic Duplication)", "GUIDANCE", "STRIKE (+1)"],
    talents: ["Determined", "Martial Arts", "Tactical Support", "Warning Call"] },
  { name: "Green Ghost", asOf: "Before the Omni-Man attack", role: "Wildcard", occupation: "Adventurer",
    descriptor: "Jade-stone transformer still learning the ropes.",
    personality: ["Plucky", "Humble"], drive: "Validation.", flaw: "Novice.", reputation: 4, resources: 5,
    attrs: A(6, 5, 5, 3, 3, 3), altAttrs: A(3, 3, 3, 3, 3, 3),
    health: 8, altHealth: 5, resolve: 7, slugfest: 3, altSlugfest: 2,
    powerSource: "Jade stone transformation",
    powers: ["FLIGHT (2 zones)", "INTANGIBILITY (Boosts: Controlled Phasing, Prolonged Phasing, Shared Intangibility)",
      "LIFE SUPPORT", "Major TELEKINESIS (weight rating 6)"],
    talents: ["Determined", "Find Weakness"],
    drawbacks: ["Alternate Form: transforming is a full action costing 1 stress and lasts a few hours."] },
  { name: "The Immortal", asOf: "Leading the new Guardians", role: "Defender", occupation: "Adventurer",
    descriptor: "Millennia-old living legend, blunt and unyielding.",
    personality: ["Heroic", "Blunt"], drive: "Peace.", flaw: "Out of touch.", reputation: 8, resources: 6,
    attrs: A(9, 6, 9, 4, 6, 6), health: 22, resolve: 14, slugfest: 5,
    powerSource: "Cosmic anomaly",
    powers: ["Major FLIGHT (4 zones; Boost: Interstellar Flight)", "Monstrous IMMORTALITY (returns within minutes unless beheaded)",
      "LIFE SUPPORT", "Massive PROTECTION (Armor 4)", "QUICKNESS", "REGENERATION"],
    talents: ["Charger", "Combat Veteran", "Commander", "Determined ×3", "Durable ×5", "Guardian", "Indomitable", "Leader", "Resilience", "Tactical Support"] },
  { name: "Invincible", asOf: "The Omni-Man incident", role: "Defender", occupation: "Student",
    descriptor: "Half-Viltrumite hero with something to prove.",
    personality: ["Courageous", "Dedicated"], drive: "Responsibility.", flaw: "Impulsive.", reputation: 4, resources: 2,
    attrs: A(7, 8, 9, 2, 4, 5), health: 14, resolve: 8, slugfest: 5,
    powerSource: "Viltrumite hybrid physiology",
    powers: ["Major FLIGHT (4 zones)", "LIFE SUPPORT", "Major PROTECTION (Armor 3)", "QUICKNESS"],
    talents: ["Determined", "Durable", "Indomitable", "Lucky Break"],
    drawbacks: ["Targeted: an interstellar empire has ordered him to prepare his world for invasion, or else."] },
  { name: "Kid Omni-Man", asOf: "First encounter with Invincible", role: "Striker", occupation: "Student",
    descriptor: "Fast-growing half-Viltrumite adolescent.",
    personality: ["Bright", "Curious"], drive: "Betterment.", flaw: "Headstrong.", reputation: 1, resources: 2,
    attrs: A(4, 5, 5, 6, 4, 4), health: 9, resolve: 9, slugfest: 3,
    powerSource: "Hybrid physiology",
    powers: ["FLIGHT (2 zones)", "LIFE SUPPORT", "PROTECTION (Armor 2)", "QUICKNESS"],
    talents: ["Determined", "Durable", "Hard Hitter"] },
  { name: "Kid Thor", asOf: "Joining the Guardians of the Globe", role: "Striker", occupation: "Adventurer",
    descriptor: "Hammer-wielding heir to a heroic legacy.",
    personality: ["Eager", "Diligent"], drive: "Legacy.", flaw: "Bellicose.", reputation: 2, resources: 4,
    attrs: A(6, 5, 7, 2, 4, 4), altAttrs: A(3, 3, 4, 2, 4, 4),
    health: 9, altHealth: 5, resolve: 5, slugfest: 6, altSlugfest: 2,
    powerSource: "Enchanted hammer",
    powers: ["Major SIGNATURE ITEM (hammer, +3 dice to STRENGTH; Limit: Item Dependent)", "LEAPING (2 zones)",
      "PROTECTION (Armor 2)", "Major STRIKE (+2)"],
    talents: ["Indomitable", "Mighty"] },
  { name: "Kinetic", asOf: "Being cured of vampirism", role: "Blaster", occupation: "Adventurer",
    descriptor: "Motion-manipulating team leader making up for lost time.",
    personality: ["Inspiring", "Intense"], drive: "Recovery.", flaw: "Vindictive.", reputation: 2, resources: 4,
    attrs: A(6, 7, 3, 3, 3, 5), health: 8, resolve: 8, slugfest: 3,
    powerSource: "Motion manipulation",
    powers: ["BARRIER (Armor 3)", "BLAST (Damage 3, Range 0/3)", "FLIGHT (2 zones)", "PROTECTION (Armor 2)",
      "STRIKE (+1)", "Major TELEKINESIS (weight rating 6)"],
    talents: ["Deflection", "Determined"],
    drawbacks: ["Reliant (alcohol)"] },
  { name: "Knockout", asOf: "Joining the Guardians of the Globe", role: "Striker", occupation: "Athlete",
    descriptor: "Legacy brawler powered by inherited gloves.",
    personality: ["Earnest", "Sassy"], drive: "Conscience.", flaw: "Restless.", reputation: 2, resources: 4,
    attrs: A(7, 7, 7, 2, 3, 4), altAttrs: A(4, 4, 4, 2, 3, 4),
    health: 11, altHealth: 6, resolve: 5, slugfest: 5, altSlugfest: 2,
    powerSource: "Boxing gloves",
    powers: ["Major SIGNATURE ITEM (gloves, +3 dice to FIGHTING; Limit: Item Dependent)", "LEAPING (2 zones)",
      "PROTECTION (Armor 2)", "STRIKE (+1; Boost: Sudden Strike)"],
    talents: ["Hard Hitter", "Second Wind"] },
  { name: "Martian Man", asOf: "Guardians of the Globe founding", role: "Wildcard", occupation: "Outsider",
    descriptor: "Shapeshifting exile serving his adopted world.",
    personality: ["Kind", "Lonely"], drive: "Benevolence.", flaw: "Peculiar.", reputation: 5, resources: 3,
    attrs: A(6, 3, 3, 4, 4, 6), health: 6, resolve: 7, slugfest: 2,
    powerSource: "Enhanced Martian physiology",
    powers: ["ELONGATION", "FLIGHT (2 zones)", "PROTECTION (Armor 2)", "REGENERATION", "SHAPESHIFTING",
      "Major SIZE ALTERATION (Limit: Grow Only)", "TELEPATHY"],
    talents: ["Subdue", "Unconventional Wisdom"] },
  { name: "Mecha-Maid", asOf: "Restoration of the Actioneers", role: "Controller", occupation: "Technician",
    descriptor: "Sentient robot exploring what it means to be alive.",
    personality: ["Adaptable", "Inquisitive"], drive: "Essence.", flaw: "Automated.", reputation: 2, resources: 5,
    attrs: A(5, 5, 5, 8, 4, 3), health: 8, resolve: 8, slugfest: 3,
    powerSource: "Robotic nature",
    powers: ["BLAST (Damage 3, Range 0/3)", "DETECTION", "ELONGATION", "FLIGHT (2 zones)", "LIFE SUPPORT",
      "PROTECTION (Armor 2; Boost: Impervious)", "REGENERATION", "TECHNOLOGY CONTROL"],
    talents: ["Analysis", "Supportive"] },
  { name: "Red Rush", asOf: "First Omnipotus encounter", role: "Striker", occupation: "Adventurer",
    descriptor: "Supersonic speedster, selfless and overwhelming.",
    personality: ["Dynamic", "Energetic"], drive: "Gallantry.", flaw: "Impatient.", reputation: 5, resources: 4,
    attrs: A(7, 5, 4, 3, 4, 3), health: 8, resolve: 7, slugfest: 3,
    powerSource: "Enhanced physiology",
    powers: ["QUICKNESS", "STRIKE (+1; Boost: Sudden Strike)", "Massive SUPER-SPEED (8 zones; Boost: Untouchable Speed)"],
    talents: ["Determined", "Fast Reflexes"] },
  { name: "Rex Splode", asOf: "Joining the Guardians of the Globe", role: "Wildcard", occupation: "Secret Agent",
    descriptor: "Explosive-charging wisecracker who gets the job done.",
    personality: ["Sardonic", "Arrogant"], drive: "Recognition.", flaw: "Abrasive.", reputation: 2, resources: 2,
    attrs: A(6, 7, 4, 2, 5, 6), health: 9, resolve: 7, slugfest: 2,
    powerSource: "Government experiment",
    powers: ["Major BLAST (Damage 4, Range 0/4; Boosts: Burst Effect, Quick Blast)", "LEAPING (2 zones)"],
    talents: ["Evasive", "Rapid Fire"] },
  { name: "Robot", asOf: "Leading the Guardians of the Globe", role: "Leader", occupation: "Technician",
    descriptor: "Hyper-intelligent strategist operating a remote automaton.",
    personality: ["Calculating", "Eloquent"], drive: "Mastery.", flaw: "Condescending.", reputation: 2, resources: 5,
    attrs: A(4, 4, 5, 9, 5, 4), altAttrs: A(1, 1, 1, 9, 5, 4),
    health: 7, altHealth: 2, resolve: 9, slugfest: 3, altSlugfest: 1,
    powerSource: "Hypercognition / robotic automaton",
    powers: ["ACTION PLAN", "BLAST (Damage 3, Range 0/3)", "DETECTION", "FLIGHT (2 zones)", "PROTECTION (Armor 2)"],
    talents: ["Analysis", "Tactical Support"],
    drawbacks: ["Robotic Automaton: if broken while operating the automaton it is destroyed and cannot be rallied (no crit roll). Without it he cannot move, his physical attributes drop to 1 and he loses every power except ACTION PLAN (comms still work). A new automaton is built automatically in a few hours."] },
  { name: "Shapesmith", asOf: "Joining the Guardians of the Globe", role: "Wildcard", occupation: "Outsider",
    descriptor: "Enthusiastic Martian newcomer learning Earth's customs.",
    personality: ["Enthusiastic", "Naive"], drive: "Belonging.", flaw: "Immature.", reputation: 2, resources: 3,
    attrs: A(5, 5, 5, 3, 2, 5), health: 10, resolve: 5, slugfest: 3,
    powerSource: "Martian physiology",
    powers: ["ELONGATION (Boosts: Elongated Stride, Plasticity, Stretch Grapple)", "REGENERATION", "SHAPESHIFTING",
      "Major SIZE ALTERATION (Limit: Grow Only)"],
    talents: ["Durable", "Subdue", "Unconventional Wisdom"] },
  { name: "Shrinking Ray", asOf: "Guardians roster", role: "Wildcard", occupation: "Secret Agent",
    descriptor: "Miniaturising infiltrator determined to make an outsized impact.",
    personality: ["Loyal", "Clever"], drive: "Esteem.", flaw: "Envious.", reputation: 2, resources: 4,
    attrs: A(8, 7, 4, 3, 4, 4), health: 10, resolve: 8, slugfest: 3,
    powerSource: "Size reduction",
    powers: ["Major SIZE ALTERATION (Limit: Shrink Only)", "STRIKE (+1; Boosts: Piercing Strike, Sudden Strike)"],
    talents: ["Determined", "Discretion", "Stealthy", "Supportive"] },
  { name: "Tech Jacket", asOf: "After the Kresh war", role: "Defender", occupation: "Student",
    descriptor: "Teenager bonded to an extraordinarily advanced battle-suit.",
    personality: ["Caring", "Fun-loving"], drive: "Guardianship.", flaw: "Awkward.", reputation: 4, resources: 5,
    attrs: A(7, 9, 9, 4, 6, 4), altAttrs: A(4, 5, 5, 4, 6, 4),
    health: 15, altHealth: 9, resolve: 9, slugfest: 7, altSlugfest: 3,
    powerSource: "Alien powersuit",
    powers: ["BARRIER (Armor 3)", "Massive BLAST (Damage 5, Range 0/5; Boost: Burst Effect)", "DETECTION",
      "ENHANCED SENSES", "Massive FLIGHT (8 zones; Boost: Interstellar Flight)", "LIFE SUPPORT",
      "Massive PROTECTION (Armor 4)", "QUICKNESS", "Major STRIKE (+2)"],
    talents: ["Determined", "Durable", "Guardian", "Resilience"],
    drawbacks: ["Targeted (a vengeful alien power)",
      "Super Suit: activating it is a full action and it can be worn a few hours. Without it he has no powers and the reduced scores apply. Broken while wearing it, the suit needs repair (REASON roll, full action) before reuse."] },
  { name: "War Woman", asOf: "Guardians of the Globe founding", role: "Striker", occupation: "Soldier",
    descriptor: "Otherworldly princess and peerless close-quarters warrior.",
    personality: ["Decisive", "Valorous"], drive: "Altruism.", flaw: "Stern.", reputation: 5, resources: 7,
    attrs: A(10, 6, 8, 4, 5, 5), health: 16, resolve: 9, slugfest: 6,
    powerSource: "Otherworldly physiology / mastery of war",
    powers: ["Major FLIGHT (4 zones)", "Major PROTECTION (Armor 3)", "QUICKNESS", "Major STRIKE (+2; Boost: Piercing Strike)"],
    talents: ["Determined", "Durable ×2", "Formidable", "Resilience", "Tactical Support"] },
  { name: "Wolf-Man", asOf: "Taking up the mantle", role: "Striker", occupation: "Privileged",
    descriptor: "Wealthy lycanthrope who transforms at will.",
    personality: ["Generous", "Persevering"], drive: "Family.", flaw: "Short-tempered.", reputation: 3, resources: 8,
    attrs: A(8, 5, 8, 3, 6, 4), altAttrs: A(4, 5, 4, 3, 3, 4),
    health: 13, altHealth: 9, resolve: 7, altResolve: 5, slugfest: 5, altSlugfest: 2,
    powerSource: "Lycanthropy",
    powers: ["ENHANCED SENSES", "LEAPING (2 zones)", "PROTECTION (Armor 2)", "QUICKNESS",
      "REGENERATION (not against silver)", "STRIKE (+1; Boost: Deadly Strike)"],
    talents: ["Durable", "Formidable", "Windfall"],
    drawbacks: ["Alternate Form: transforming is a full action costing 1 stress and lasts a few hours.",
      "Lunar Frenzy: on a full moon he transforms and attacks anything nearby, fighting until broken or until all enemies flee or are broken, refusing surrender and unable to pull punches. Anyone restraining him becomes the next target unless he takes 3 stress to regain control.",
      "Vulnerable (Silver): double damage, and REGENERATION stops working for the rest of the scene."] },
];

export const PREGEN_NOTE =
  "These are published character stat blocks, not point-built heroes. Their Health, Resolve and " +
  "Slugfest Damage are used as printed. The app flags them as pregens so creation-legality checks " +
  "are not applied to them retroactively.";
