// data-npcs.js — Ch.6 stock NPC profiles, animals, and the NPC build recipe.
// Mechanics extracted verbatim in value; descriptive text paraphrased.

export const NPC_HANDLING = [
  "NPCs use the same mechanics as heroes, but ignore those mechanics unless a player character is directly affected — otherwise just decide what happens.",
  "Don't roll dice for NPC actions unless they attack or interact with a player character.",
  "Major NPCs may push rolls like heroes, but should do so sparingly.",
  "When an NPC is broken you need not roll a critical injury; declare them knocked out or killed. Major NPCs roll crits normally.",
  "Minions are generic characters with identical stats handled as a single entity for movement, attacks, Health and Resolve.",
];

export const NPC_RECIPE = [
  { step: "Attributes", desc: "Start from a profile and adjust, or set scores to whatever fits the concept." },
  { step: "Powers", desc: "Only give an NPC powers they are likely to actually use. Swapping powers at the same level is free." },
  { step: "Talents", desc: "Many NPCs have none; add them to customise." },
  { step: "Drawbacks", desc: "Useful when you want the heroes to be able to discover a vulnerability." },
  { step: "Special Abilities", desc: "Unique traits or unusual actions tied to the NPC's role in the story." },
  { step: "Personal stuff", desc: "Name (and whether their identity is public), appearance and quirks, drive, flaw, and how others perceive them." },
];

// attrs order: fighting, agility, strength, reason, intuition, presence
const A = (f, a, s, r, i, p) => ({ fighting: f, agility: a, strength: s, reason: r, intuition: i, presence: p });

export const NPC_PROFILES = [
  { name: "Assassin", role: "Blaster", occupation: "Secret Agent", desc: "A professional killer, hired gun or contract killer.",
    drive: "Vocation. Assassins kill who they are paid to kill.",
    attrs: A(5, 5, 4, 2, 4, 3), health: 7, resolve: 5, slugfest: 2,
    talents: ["Killer", "Sniper", "Stealthy"],
    gear: ["Sniper rifle (Bonus +2, Damage 3, Range 1/10)", "Handgun (Bonus +1, Damage 2, Range 0/1)", "Mobile phone"] },
  { name: "Athlete", role: "Brawn", occupation: "Athlete", desc: "A sports star, professional wrestler or Olympic competitor.",
    drive: "Recognition. Athletes train and compete for the roar of the crowd.",
    attrs: A(4, 5, 5, 2, 2, 3), health: 7, resolve: 4, slugfest: 3,
    talents: ["Coordinated", "Motivator"], gear: ["Mobile phone", "Training equipment"] },
  { name: "Atlantean Warriors", minion: true, role: "Striker", occupation: "Soldier", desc: "Typical members of the Atlantean military.",
    drive: "Responsibility. Atlantean warriors dutifully serve their kingdom.",
    attrs: A(5, 4, 6, 2, 4, 2), health: 1, resolve: 4, slugfest: 3,
    powerSource: "Atlantean physiology — adapted to the cold dark of the ocean depths.",
    powers: ["IMMUNITY (cold)", "PROTECTION (Armor 2)", "Major SWIMMING — 4 zones in a single action"],
    talents: ["Combat Veteran", "Tactical Support"],
    drawbacks: ["Water Breather: they breathe water normally, but only a few hours of air before suffocating as in a vacuum without equipment. Each hour out of water also costs -1 die to STRENGTH and AGILITY rolls."],
    gear: ["Atlantean spear (Bonus +1, Damage 2, sharp)", "Concussion blaster (Bonus +1, Damage 2, Range 0/1)", "Oxygen mask (a few hours of air)"] },
  { name: "Automaton", role: "Blaster", occupation: "Technician", desc: "A robot, android or drone.",
    drive: "Programming. Automatons follow the behavior of their coding.",
    attrs: A(5, 5, 5, 5, 2, 2), health: 8, resolve: 5, slugfest: 3,
    powerSource: "Robotic components.",
    powers: ["BLAST (Damage 3, Range 0/3)", "DETECTION", "FLIGHT (2 zones, 4 for 1 stress)", "PROTECTION (Armor 2)"],
    talents: ["Analysis", "Rapid Fire"] },
  { name: "Bystanders", minion: true, desc: "Everyday people just living their lives.",
    attrs: A(2, 2, 2, 2, 2, 2), health: 1, resolve: 3, slugfest: 1, gear: ["Mobile phone"] },
  { name: "Commando", role: "Striker", occupation: "Soldier", desc: "A special forces soldier, guerrilla warrior or mercenary.",
    drive: "Duty. Commandos fulfill their responsibilities as special forces operators.",
    attrs: A(5, 4, 5, 2, 5, 2), health: 7, resolve: 5, slugfest: 3,
    talents: ["Combat Veteran", "Stealthy", "Tactical Support"],
    gear: ["Assault rifle (Bonus +1, Damage 3, Range 0/4, full auto)", "Handgun (Bonus +1, Damage 2, Range 0/1)", "Flak vest (Armor 1)", "Night vision goggles", "Radio"] },
  { name: "Covert Operative", role: "Wildcard", occupation: "Secret Agent", desc: "A secret agent, spy or intelligence officer.",
    drive: "Vocation. Covert operatives run missions for pay, ideology or excitement.",
    attrs: A(5, 4, 4, 4, 4, 4), health: 7, resolve: 6, slugfest: 2,
    talents: ["Manipulator", "Stealthy"],
    gear: ["Handgun (Bonus +1, Damage 2, Range 0/1)", "Knife (Bonus +1, Damage 2)", "Mobile phone", "Personal supercomputer", "Nano tracer"] },
  { name: "Crime Lord", role: "Leader", occupation: "Criminal", desc: "The head of a crime syndicate, gang leader or kingpin.",
    drive: "Greed. The crime lord wants more money and power.",
    attrs: A(4, 2, 4, 4, 4, 6), health: 5, resolve: 7, slugfest: 2,
    talents: ["Discretion", "Manipulator", "Streetwise"],
    drawbacks: ["Targeted (Law Enforcement)"],
    gear: ["Handgun (Bonus +1, Damage 2, Range 0/1)", "Mobile phone"] },
  { name: "Cultists", minion: true, role: "Wildcard", occupation: "Devotee", desc: "Fanatical followers, disciples or zealots.",
    drive: "Fanaticism. Cultists zealously follow the object of their devotion.",
    attrs: A(3, 2, 2, 2, 2, 4), health: 1, resolve: 6, slugfest: 1,
    talents: ["Determined", "Knowledgeable (Esoteric Lore)"], gear: ["Dagger (Bonus +1, Damage 2)"] },
  { name: "Demon", role: "Wildcard", occupation: "Outsider", desc: "A denizen of Hell loose upon the surface world.",
    drive: "Corruption. A demon is sustained by degenerating mortal souls.",
    attrs: A(6, 5, 6, 5, 2, 6), health: 13, resolve: 13, slugfest: 3,
    powerSource: "Demonic physiology.",
    powers: ["DIMENSIONAL TRAVEL (Boost: Quick Travel; Limit: Hell only)", "ENHANCED SENSES", "IMMUNITY (heat)",
      "IMMORTALITY — cannot die unless killed in Hell", "LIFE SUPPORT", "PROTECTION (Armor 2)", "REGENERATION",
      "TELEPORTATION (2 zones; Boost: Distant Travel)"],
    talents: ["Determined ×3", "Durable ×2", "Hard Hitter", "Manipulator", "Menacing", "Resilience"],
    drawbacks: ["Frightful: -3 dice on PRESENCE rolls to persuade, unless intimidating.",
      "Banishment: can be exorcised back to Hell by an arcane ritual known to the magical elite.",
      "Vulnerable (Iron): double damage from iron attacks."] },
  { name: "Detective", role: "Brains", occupation: "Investigator", desc: "A police detective or private investigator.",
    drive: "Answers. The detective follows the evidence wherever it leads.",
    attrs: A(4, 3, 3, 4, 5, 4), health: 5, resolve: 7, slugfest: 2,
    talents: ["Investigator", "Streetwise"],
    gear: ["Handgun (Bonus +1, Damage 2, Range 0/1)", "Handcuffs", "Mobile phone"] },
  { name: "Doctor", role: "Brains", occupation: "Medic", desc: "A medical professional, general practitioner or surgeon.",
    drive: "Healing. A doctor works to help others maintain good health.",
    attrs: A(2, 2, 2, 4, 4, 2), health: 3, resolve: 5, slugfest: 1,
    talents: ["Knowledgeable (Natural Sciences)", "Medic"], gear: ["Medical instruments", "Mobile phone"] },
  { name: "Flaxan Invaders", minion: true, role: "Blaster", occupation: "Soldier", desc: "Foot soldiers in the Flaxan armies.",
    drive: "Domination. Flaxan invaders subjugate other worlds to power their expansion.",
    attrs: A(4, 4, 4, 2, 2, 2), health: 1, resolve: 3, slugfest: 2,
    talents: ["Rapid Fire", "Tactical Support"],
    drawbacks: ["Accelerated Aging (unique): outside their home dimension Flaxans age roughly ten thousand times faster — minutes here can mean months. Their technology offsets this temporarily; remove the protection and natural aging returns, and catches up, almost instantly."],
    gear: ["Blast pistol (Bonus +1, Damage 2, Range 0/2)", "Blast rifle (Bonus +1, Damage 3, Range 1/8, full auto)", "Trooper armor (Armor 2)", "Chrono-band (negates Accelerated Aging while working)", "Communicator"] },
  { name: "Gangsters", minion: true, role: "Blaster", occupation: "Criminal", desc: "Professional criminals or mobsters.",
    drive: "Respect. Gangsters chase wealth and status to be recognised.",
    attrs: A(4, 4, 3, 2, 2, 2), health: 1, resolve: 3, slugfest: 2,
    talents: ["Merciless"],
    gear: ["Assault rifle (Bonus +1, Damage 3, Range 0/4, full auto)", "Brass knuckles (Bonus +1, Damage 2)", "Mobile phone"] },
  { name: "Magmanite Underworlders", minion: true, role: "Brawn", occupation: "Outsider",
    desc: "Living magma creatures from deep below the surface; these are the most commonly seen specimens — more powerful ones exist.",
    drive: "Purpose. Magmanites crave a meaningful existence in a harsh environment.",
    attrs: A(4, 2, 6, 2, 2, 2), health: 1, resolve: 3, slugfest: 3,
    powerSource: "Magmanite physiology — lava-composed bodies.",
    powers: ["BLAST (Damage 3, Range 0/3)", "EMANATION (+2 Slugfest Damage, 3 damage to anyone touching)", "IMMUNITY (heat)", "PROTECTION (Armor 2)"],
    talents: ["Hard Hitter", "Menacing"],
    drawbacks: ["Vulnerable (Cold): double damage from cold attacks."] },
  { name: "Martial Artists", minion: true, role: "Striker", occupation: "Adventurer", desc: "Fighters trained in kung fu, muay thai or another discipline.",
    drive: "Self-improvement. Martial artists want to overcome external and internal challenges.",
    attrs: A(5, 5, 4, 2, 4, 2), health: 1, resolve: 4, slugfest: 3,
    powerSource: "Martial arts mastery.",
    powers: ["STRIKE (+1 Slugfest Damage, halve armor for 1 stress; Boost: Sudden Strike)"],
    talents: ["Fast Reflexes", "Martial Arts", "Subdue"] },
  { name: "Martian Scouts", minion: true, role: "Wildcard", occupation: "Secret Agent", desc: "The first line of detection for the people of Mars.",
    drive: "Responsibility. Martian scouts serve at the behest of the Martian emperor.",
    attrs: A(4, 4, 4, 2, 4, 2), health: 1, resolve: 4, slugfest: 2,
    powerSource: "Martian physiology — metamorphic capabilities.",
    powers: ["ELONGATION (Boost: Elongated Stride)", "REGENERATION", "SHAPESHIFTING"],
    talents: ["Stealthy", "Subdue"],
    gear: ["Energy pistol (Bonus +1, Damage 2, Range 0/2, full auto)", "Stun grenades (Damage 3, Range 0/1, area effect, STUN)", "Scout biosuit (Armor 1)", "Communicator"] },
  { name: "News Reporter", role: "Wildcard", occupation: "Investigator", desc: "A media specialist, beat reporter or blogger.",
    drive: "Truth. To disclose the facts to the masses.",
    attrs: A(2, 3, 2, 4, 5, 4), health: 4, resolve: 7, slugfest: 1,
    talents: ["Knowledgeable (Humanities)", "Investigator"],
    gear: ["Pepper spray (Bonus +2, Damage 1, Range 0/0, STUN)", "Mobile phone"] },
  { name: "Ninjas", minion: true, role: "Striker", occupation: "Secret Agent", desc: "Dangerous foes trained in the art of ninjutsu.",
    drive: "Greed. Ninjas work for whoever can afford their exorbitant rates.",
    attrs: A(6, 6, 4, 4, 5, 4), health: 1, resolve: 7, slugfest: 3,
    powerSource: "Ninjutsu.",
    powers: ["DISTRESS — shuriken, smoke bombs and fear tactics inflicting 3 stress, Range 0/3",
      "STRIKE (+1 Slugfest Damage, halve armor for 1 stress; Boost: Sudden Strike)", "SWINGING (2 zones)"],
    talents: ["Fast Reflexes", "Martial Arts", "Subdue"],
    gear: ["Katana (Bonus +1, Damage 2, sharp)", "Smoke grenades"] },
  { name: "Police Chief", role: "Leader", occupation: "Law Enforcer", desc: "A police official leading a department.",
    drive: "Peace. The police chief wants peace — for the public and from the politicians.",
    attrs: A(4, 2, 3, 4, 4, 4), health: 5, resolve: 6, slugfest: 2,
    talents: ["Commander", "Inspiration", "Motivator"],
    drawbacks: ["Targeted (Criminal Element)"],
    gear: ["Handgun (Bonus +1, Damage 2, Range 0/1)", "Mobile phone"] },
  { name: "Police Officers", minion: true, role: "Blaster", occupation: "Law Enforcer", desc: "Members of law enforcement or beat cops.",
    drive: "Vocation. Police officers are paid to serve and protect.",
    attrs: A(3, 3, 3, 2, 3, 2), health: 1, resolve: 4, slugfest: 2,
    talents: ["Guardian", "Subdue"],
    gear: ["Handgun (Bonus +1, Damage 2, Range 0/1)", "Taser (Bonus +1, Damage 2, Range 0/0, STUN)", "Handcuffs", "Radio"] },
  { name: "Politician", role: "Leader", occupation: "Public Servant", desc: "A city council member, legislator, delegate or emissary.",
    drive: "Calling. Politicians believe they are intended for higher office.",
    attrs: A(2, 2, 2, 4, 2, 4), health: 3, resolve: 5, slugfest: 1,
    talents: ["Discretion", "Supportive"], gear: ["Mobile phone"] },
  { name: "Rognarr", role: "Brawn", huge: true, desc: "Ferocious alien beasts — one of the few creatures Viltrumites fear.",
    drive: "Instinct. Rognarrs act on primal impulses to destroy any living thing near them.",
    attrs: A(9, 7, 10, 1, 6, 6), health: 21, resolve: 13, slugfest: 8,
    powerSource: "Rognarr physiology — evolved on a high-gravity world.",
    powers: ["Massive LEAPING (8 zones)", "LIFE SUPPORT (survives space)", "Monstrous PROTECTION (Armor 5)", "QUICKNESS",
      "Massive STRIKE (+3 Slugfest Damage; Boosts: Deadly Strike, Sudden Strike)"],
    talents: ["Determined ×3", "Durable ×4", "Fast Reflexes", "Formidable", "Hard Hitter"],
    drawbacks: ["Bloodlust"] },
  { name: "Scientist", role: "Brains", occupation: "Scientist", desc: "A specialist in a specific field of study.",
    drive: "Discovery. A scientist seeks to solve the mysteries of the natural world.",
    attrs: A(2, 2, 2, 5, 2, 2), health: 3, resolve: 5, slugfest: 1,
    talents: ["Analysis", "Knowledgeable (Natural Sciences)"], gear: ["Mobile phone", "Laboratory instruments"] },
  { name: "Sequid Swarm", minion: true, role: "Controller",
    desc: "A swarm of dozens of parasitic Sequids occupying a zone and acting together. Multiple swarms can share a zone and help one another.",
    drive: "Domination. Sequids live to control and overwhelm other species.",
    attrs: A(5, 7, 5, 6, 5, 5), health: 1, resolve: 8, slugfest: 3,
    powerSource: "Sequid physiology — highly effective parasites.",
    powers: ["LEAPING (2 zones)", "LIFE SUPPORT (survives vacuum)", "MIND CONTROL (Boost: Area Control; Limit: Requires Touch)",
      "PROTECTION (Armor 2)", "QUICKNESS", "TELEPATHY (Boost: Memory Alteration; Limit: Read Only)"],
    talents: ["Duck & Weave", "Evasive", "Resilience"],
    drawbacks: ["Power Loss: without a host the Sequids lose access to their powers."],
    special: ["Hive Mind: with even a single host they share a psychic link and are instantly aware of anything happening to other Sequids on the same planet."] },
  { name: "Shocktroopers", minion: true, role: "Blaster", occupation: "Soldier", desc: "Highly trained and better equipped soldiers.",
    drive: "Duty. Shocktroopers fulfill their responsibilities in specialised units.",
    attrs: A(5, 4, 4, 2, 2, 2), health: 1, resolve: 3, slugfest: 2,
    talents: ["Combat Veteran", "Rapid Fire", "Tactical Support"],
    gear: ["Plasma rifle (Bonus +2, Damage 3, Range 0/3, full auto)", "Short blade (Bonus +1, Damage 2, sharp)", "Hand grenades (Damage 3, Range 0/1, area effect)", "Trooper armor (Armor 2)", "Radio"] },
  { name: "Soldiers", minion: true, role: "Blaster", occupation: "Soldier", desc: "Enlisted combatants or infantry.",
    drive: "Duty. Soldiers fulfill their responsibilities in their combat units.",
    attrs: A(4, 3, 4, 2, 2, 2), health: 1, resolve: 3, slugfest: 2,
    talents: ["Guardian", "Tactical Support"],
    gear: ["Assault rifle (Bonus +1, Damage 3, Range 0/4, full auto)", "Handgun (Bonus +1, Damage 2, Range 0/1)", "Knife (Bonus +1, Damage 2)", "Flak vest (Armor 1)", "Radio"] },
  { name: "Thugs", minion: true, role: "Brawn", occupation: "Criminal", desc: "Common criminals, bullies, ruffians or cutthroats.",
    drive: "Opportunism. Thugs take what they can, however they can.",
    attrs: A(3, 3, 3, 1, 2, 2), health: 1, resolve: 3, slugfest: 2,
    talents: ["Merciless"],
    gear: ["Handgun (Bonus +1, Damage 2, Range 0/1) or knife (Bonus +1, Damage 2)", "Mobile phone"] },
  { name: "Vampire", role: "Striker", desc: "A bloodsucking creature of the night.",
    drive: "Control. A vampire seeks to control their circumstances, those around them, and their own impulses.",
    attrs: A(6, 7, 6, 2, 6, 5), health: 10, resolve: 7, slugfest: 4,
    powerSource: "Vampirism.",
    powers: ["IMMORTALITY — permanently killed only by decapitation, staking, or eating the heart",
      "INTANGIBILITY (gray mist)", "LEAPING (2 zones)", "MIND CONTROL (Boost: Area Control; Limit: Hypnosis)",
      "PROTECTION (Armor 2)", "QUICKNESS", "REGENERATION",
      "SHAPESHIFTING (Boost: Potent Form; Limit: Specific Form — bat)",
      "STRIKE (+1 Slugfest Damage, halve armor for 1 stress; Boost: Sudden Strike)"],
    talents: ["Fast Reflexes", "Resilience", "Stealthy"],
    drawbacks: ["Reliant (Blood): a PRESENCE roll every few hours without blood; failure costs 1 stress, blocks Resolve recovery and gives a cumulative -1 die to all attribute rolls.",
      "Weakness to Sunlight: D6 damage per round in direct sunlight, ignoring armor."],
    special: ["Vampiric Turn: if the GM chooses, a vampire can spend a few minutes draining a broken target and feeding them vampiric blood; the victim rises as a vampire within minutes."] },
  { name: "Werewolf", role: "Brawn", desc: "A cursed person who transforms into a walking wolf.",
    drive: "Fury. A werewolf acts on instinctual rage.",
    attrs: A(6, 5, 7, 2, 2, 2), altAttrs: A(3, 3, 4, 2, 2, 2),
    health: 9, altHealth: 5, resolve: 5, slugfest: 5, altSlugfest: 2,
    powerSource: "Lycanthropy — the full moon grants superhuman strength, agility, healing and vicious claws. Some werewolves learn to transform at will.",
    powers: ["ENHANCED SENSES", "LEAPING (2 zones)", "PROTECTION (Armor 2)", "QUICKNESS",
      "REGENERATION (not against silver)", "STRIKE (+1 Slugfest Damage; Boost: Deadly Strike)"],
    talents: ["Determined", "Menacing", "Second Wind"],
    drawbacks: ["Alternate Form: transforming is a full action costing 1 stress, lasting a few hours. In human form the reduced scores apply and there are no powers.",
      "Lunar Frenzy: on a full moon they transform and attack anything nearby, fighting until broken or until all enemies flee or are broken, refusing surrender and unable to pull punches. Anyone restraining them becomes the next target unless they take 3 stress to regain control.",
      "Vulnerable (Silver): double damage, and REGENERATION stops working for the rest of the scene."],
    special: ["Curse of Lycanthropy: should the GM wish, a werewolf's victim falls comatose until the next full moon, then transforms."] },
  { name: "Zombies", minion: true, role: "Wildcard", desc: "Members of the walking dead.",
    drive: "Brains. Raaagrh!",
    attrs: A(4, 2, 4, 1, 1, 1), health: 1, resolve: 2, slugfest: 3,
    powerSource: "Zombification.",
    powers: ["DEFIANCE — mindless, resists mental control", "PROTECTION (Armor 2)", "STRIKE (+1 Slugfest Damage, halve armor for 1 stress)"],
    talents: ["Hard Hitter"],
    drawbacks: ["Mindless (unique): zombies automatically fail REASON and PRESENCE rolls."],
    special: ["Zombie Contagion: if the GM desires, anyone killed by a zombie rises as one within minutes unless cured."] },
];

export const CREATURES = [
  { name: "Bat", attrs: A(3, 6, 1, 1, 4, 2), health: 5, traits: ["ADHESION", "DANGER SENSE", "ENHANCED SENSES", "FLIGHT", "Evasive"] },
  { name: "Bear", attrs: A(5, 3, 6, 1, 6, 3), health: 9, traits: ["ENHANCED SENSES (smell only)", "Major STRIKE", "Charger", "Durable"] },
  { name: "Big Cat", attrs: A(4, 6, 4, 1, 4, 3), health: 7, traits: ["ENHANCED SENSES", "LEAPING", "STRIKE (+1)", "Charger", "Stealthy"] },
  { name: "Bird, predator", attrs: A(3, 6, 2, 1, 5, 3), health: 6, traits: ["ENHANCED SENSES (sight only)", "Major FLIGHT", "STRIKE (+1)", "Charger", "Evasive"] },
  { name: "Crocodile", attrs: A(5, 2, 4, 1, 5, 2), health: 8, traits: ["CAMOUFLAGE", "ENHANCED SENSES", "STRIKE (+1)", "Major SWIMMING", "Durable"] },
  { name: "Dinosaur, sauropod", attrs: A(3, 2, 8, 1, 2, 2), health: 13, traits: ["ENHANCED SENSES", "Major PROTECTION (Armor 3)", "STRIKE (+1)", "Durable ×3"] },
  { name: "Dinosaur, raptor", attrs: A(6, 4, 3, 1, 4, 2), health: 7, traits: ["ENHANCED SENSES", "LEAPING", "STRIKE (+1)", "Evasive", "Stealthy", "Supportive"] },
  { name: "Dinosaur, triceratops", attrs: A(4, 2, 6, 1, 3, 3), health: 10, traits: ["ENHANCED SENSES", "Massive PROTECTION (Armor 4)", "Major STRIKE (+2)", "Charger", "Durable ×2"] },
  { name: "Dinosaur, tyrannosaur", attrs: A(6, 3, 7, 1, 3, 3), health: 10, traits: ["ENHANCED SENSES", "Major PROTECTION (Armor 3)", "Massive STRIKE (+3)", "Durable", "Menacing"] },
  { name: "Dolphin", attrs: A(2, 5, 3, 2, 4, 5), health: 5, traits: ["ENHANCED SENSES", "Major SWIMMING", "Supportive"] },
  { name: "Elephant", attrs: A(3, 2, 8, 2, 5, 4), health: 11, traits: ["ENHANCED SENSES (smell only)", "PROTECTION (Armor 2)", "STRIKE (+1)", "Charger", "Durable ×2", "Supportive"] },
  { name: "Gorilla", attrs: A(5, 4, 6, 2, 4, 3), health: 8, traits: ["STRIKE (+1)", "SWINGING (Limit: Brachiation)"] },
  { name: "Horse", attrs: A(3, 4, 5, 1, 4, 2), health: 6, traits: ["ENHANCED SENSES", "LEAPING"] },
  { name: "Snake, python", attrs: A(3, 3, 5, 1, 3, 2), health: 6, traits: ["ADHESION", "ENHANCED SENSES", "Subdue"] },
  { name: "Snake, viper", attrs: A(3, 3, 1, 1, 3, 2), health: 4, traits: ["ADHESION", "Major AFFLICTION (Limit: Requires Touch)", "ENHANCED SENSES", "Stealthy"] },
  { name: "Shark", attrs: A(5, 3, 5, 1, 4, 2), health: 7, traits: ["CAMOUFLAGE", "ENHANCED SENSES", "Major STRIKE (+2)", "Major SWIMMING"] },
  { name: "Whale", attrs: A(3, 2, 8, 2, 4, 3), health: 13, traits: ["Major SWIMMING", "Durable ×3"] },
  { name: "Wolf", attrs: A(4, 5, 3, 2, 5, 2), health: 6, traits: ["ENHANCED SENSES (smell only)", "LEAPING", "STRIKE (+1)", "Bigger They Are", "Supportive"] },
];

export const CREATURE_NOTE = "These are typical animals. Modify them for similar creatures, or use them as references for shapeshifters and summoners.";
